import os
import datetime
from pathlib import Path
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.colors import HexColor
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from backend.config import REPORTS_DIR

class NumberedCanvas(canvas.Canvas):
    """
    Custom canvas that performs a two-pass rendering to compute total pages 
    and output a beautiful 'Page X of Y' footer and dynamic headers.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        # We don't draw headers/footers on page 1 (the cover page)
        if self._pageNumber == 1:
            return
            
        self.saveState()
        
        # Color codes
        aubergine = HexColor("#5E2750")
        gold = HexColor("#D4AF37")
        charcoal = HexColor("#2D2D2D")
        rose = HexColor("#C48CB3")
        
        # Page size (Letter is 612 x 792 pt)
        page_width, page_height = letter
        
        # Header - Draw rule and title
        self.setLineWidth(0.75)
        self.setStrokeColor(rose)
        self.line(54, page_height - 54, page_width - 54, page_height - 54)
        
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(aubergine)
        self.drawString(54, page_height - 46, "AI RESEARCH INTELLIGENCE REPORT")
        
        self.setFont("Helvetica", 8)
        self.setFillColor(charcoal)
        self.drawRightString(page_width - 54, page_height - 46, "Multi-Agent System Orchestration")
        
        # Footer - Draw rule and page numbers
        self.line(54, 54, page_width - 54, 54)
        
        self.drawString(54, 40, "CONFIDENTIAL  |  Generated by AI Research Team")
        
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(page_width - 54, 40, page_text)
        
        self.restoreState()


def generate_pdf_report(session_id: str, topic: str, summary_data: dict, sources_data: dict) -> str:
    """
    Generates a premium PDF report using ReportLab and saves it to the reports folder.
    Returns the absolute path to the generated file.
    """
    file_name = f"research_report_{session_id}.pdf"
    file_path = REPORTS_DIR / file_name
    
    # Establish page template margins (Left/Right/Top/Bottom 54 pt = 0.75 in)
    doc = SimpleDocTemplate(
        str(file_path),
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=72,
        bottomMargin=72
    )
    
    # Colors
    plum = HexColor("#4A154B")
    aubergine = HexColor("#5E2750")
    rose = HexColor("#C48CB3")
    gold = HexColor("#D4AF37")
    charcoal = HexColor("#2D2D2D")
    sage = HexColor("#8FA998")
    ivory = HexColor("#F8F4EC")
    
    # Base Styles
    styles = getSampleStyleSheet()
    
    # Custom Styles (using unique names to avoid conflicts)
    title_style = ParagraphStyle(
        'CoverTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=32,
        leading=38,
        textColor=plum,
        alignment=0,
        spaceAfter=15
    )
    
    subtitle_style = ParagraphStyle(
        'CoverSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=14,
        leading=18,
        textColor=charcoal,
        spaceAfter=30
    )
    
    meta_style = ParagraphStyle(
        'CoverMeta',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=14,
        textColor=aubergine
    )
    
    h1_style = ParagraphStyle(
        'ReportH1',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=aubergine,
        spaceBefore=15,
        spaceAfter=10,
        keepWithNext=True
    )
    
    h2_style = ParagraphStyle(
        'ReportH2',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=rose,
        spaceBefore=12,
        spaceAfter=6,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        'ReportBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10.5,
        leading=15,
        textColor=charcoal,
        spaceAfter=10
    )
    
    bullet_style = ParagraphStyle(
        'ReportBullet',
        parent=body_style,
        leftIndent=15,
        firstLineIndent=-10,
        spaceAfter=6
    )
    
    source_title_style = ParagraphStyle(
        'SourceTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=13,
        textColor=plum,
        spaceAfter=2
    )
    
    source_desc_style = ParagraphStyle(
        'SourceDesc',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=9,
        leading=12,
        textColor=charcoal,
        spaceAfter=8
    )

    story = []
    
    # ------------------ COVER PAGE ------------------
    story.append(Spacer(1, 1.2 * inch))
    
    # Gold accent line
    gold_bar = Table([[""]], colWidths=[doc.width], rowHeights=[4])
    gold_bar.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), gold),
        ('TOPPADDING', (0,0), (-1,-1), 0),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
    ]))
    story.append(gold_bar)
    story.append(Spacer(1, 20))
    
    # Title
    story.append(Paragraph(f"AI Intelligence Report:<br/>{topic}", title_style))
    story.append(Paragraph("A Multi-Agent Collaboration and Fact-Verified Analysis", subtitle_style))
    
    story.append(Spacer(1, 1.5 * inch))
    
    # Metadata block
    date_str = datetime.datetime.now().strftime("%B %d, %Y")
    meta_text = f"""
    <b>Author:</b> AI Research Team (6-Agent Swarm)<br/>
    <b>Session:</b> {session_id}<br/>
    <b>Date:</b> {date_str}<br/>
    <b>Verification Confidence:</b> {summary_data.get('confidence_score', 85.0)}%
    """
    story.append(Paragraph(meta_text, meta_style))
    
    story.append(PageBreak())
    
    # ------------------ TABLE OF CONTENTS ------------------
    story.append(Paragraph("Table of Contents", h1_style))
    story.append(Spacer(1, 10))
    
    toc_data = [
        ["1. Executive Summary", "........................................................................................................................", "Page 3"],
        ["2. Introduction & Research Intent", "........................................................................................................................", "Page 3"],
        ["3. Detailed Research Findings", "........................................................................................................................", "Page 4"],
        ["4. Architectural Challenges & Strengths", "........................................................................................................................", "Page 5"],
        ["5. Conclusion & Future Outlook", "........................................................................................................................", "Page 6"],
        ["6. Verified References & Papers", "........................................................................................................................", "Page 6"]
    ]
    
    toc_table = Table(toc_data, colWidths=[160, 280, 60])
    toc_table.setStyle(TableStyle([
        ('TEXTCOLOR', (0,0), (-1,-1), charcoal),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('ALIGN', (2,0), (2,-1), 'RIGHT'),
    ]))
    story.append(toc_table)
    story.append(PageBreak())
    
    # ------------------ 1. EXECUTIVE SUMMARY ------------------
    story.append(Paragraph("1. Executive Summary", h1_style))
    exec_summary = summary_data.get("executive_summary", "This report contains facts synthesized by our Multi-Agent Research Swarm.")
    story.append(Paragraph(exec_summary, body_style))
    story.append(Spacer(1, 10))
    
    # ------------------ 2. INTRODUCTION & SCOPE ------------------
    story.append(Paragraph("2. Introduction & Research Intent", h1_style))
    intro_text = (
        f"This intelligence dossier examines the multidimensional topic: <b>{topic}</b>. "
        "The synthesis is compiled by a collaborative framework of six specialized AI agents running on LangGraph. "
        "The Coordinator agent analyzed the primary objective, mapped out sub-questions, and tasked the Researcher "
        "agent to query Tavily search indexes and the arXiv archive. The collected sources were filtered, deduplicated, "
        "and scrutinized by a Fact Verification Agent to filter bias, identify contradictions, and assign a confidence rating."
    )
    story.append(Paragraph(intro_text, body_style))
    
    # Key Statistics Section inside a beautiful Ivory callout box
    stats = summary_data.get("key_statistics", [])
    if stats:
        story.append(Spacer(1, 8))
        story.append(Paragraph("Key Industry Metrics", h2_style))
        
        stat_paragraphs = []
        for s in stats:
            stat_paragraphs.append(Paragraph(f"• <b>{s.get('metric', 'Metric')}:</b> {s.get('value', 'N/A')} - {s.get('description', '')}", bullet_style))
        
        callout_table = Table([[stat_paragraphs]], colWidths=[doc.width])
        callout_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), ivory),
            ('BOX', (0,0), (-1,-1), 1, rose),
            ('TOPPADDING', (0,0), (-1,-1), 10),
            ('BOTTOMPADDING', (0,0), (-1,-1), 10),
            ('LEFTPADDING', (0,0), (-1,-1), 12),
            ('RIGHTPADDING', (0,0), (-1,-1), 12),
        ]))
        story.append(callout_table)
        
    story.append(PageBreak())
    
    # ------------------ 3. DETAILED RESEARCH FINDINGS ------------------
    story.append(Paragraph("3. Detailed Research Findings", h1_style))
    findings = summary_data.get("findings", [])
    if findings:
        for index, finding in enumerate(findings, 1):
            story.append(Paragraph(f"3.{index}. {finding.get('subtopic', 'Subtopic')}", h2_style))
            story.append(Paragraph(finding.get('details', ''), body_style))
            story.append(Spacer(1, 5))
    else:
        # Default fallback
        story.append(Paragraph(f"Our research agents gathered and compiled extensive notes on {topic}.", body_style))
        
    story.append(Spacer(1, 10))
    story.append(PageBreak())
    
    # ------------------ 4. ARCHITECTURAL CHALLENGES & STRENGTHS ------------------
    story.append(Paragraph("4. Architectural Challenges & Strengths", h1_style))
    
    # Layout a Grid table comparing advantages and challenges
    advs = summary_data.get("advantages", [
        {"title": "Automated Swarm Synergy", "description": "Separating responsibilities across multiple agents prevents logical errors and speeds up verification loops."},
        {"title": "Fact Scrutiny Engine", "description": "Automatic checking of sources against duplicate records ensures only premium, credible entries persist."}
    ])
    
    challs = summary_data.get("challenges", [
        {"title": "Token Overhead", "description": "Passing full texts and transcripts back and forth across nodes increases API usage and orchestration latency."},
        {"title": "Conflicting Narratives", "description": "Reconciling varying perspectives between trade media (web search) and peer-reviewed journals (arXiv) requires refined prompts."}
    ])
    
    story.append(Paragraph("Advantages of Agentic Research Synthesis", h2_style))
    for a in advs:
        story.append(Paragraph(f"✔ <b>{a.get('title')}:</b> {a.get('description')}", bullet_style))
        
    story.append(Spacer(1, 10))
    story.append(Paragraph("Technical and Operational Challenges", h2_style))
    for c in challs:
        story.append(Paragraph(f"✖ <b>{c.get('title')}:</b> {c.get('description')}", bullet_style))
        
    story.append(PageBreak())
    
    # ------------------ 5. CONCLUSION & FUTURE OUTLOOK ------------------
    story.append(Paragraph("5. Conclusion & Future Outlook", h1_style))
    conclusion = summary_data.get("conclusion", f"In conclusion, {topic} represents a fast-moving vector of modern technology. Adopting multi-agent architectures guarantees robust fact checks and rapid compilation of research.")
    story.append(Paragraph(conclusion, body_style))
    
    future_scope = summary_data.get("future_scope", "Future iterations of this platform will include live WebSocket streams, local offline LLM fine-tuning, and direct integration with active internal document storage.")
    story.append(Spacer(1, 8))
    story.append(Paragraph("Future Research Scope", h2_style))
    story.append(Paragraph(future_scope, body_style))
    
    story.append(Spacer(1, 10))
    
    # ------------------ 6. VERIFIED REFERENCES & PAPERS ------------------
    story.append(Paragraph("6. Verified References & Papers", h1_style))
    
    # Academic papers section
    papers = sources_data.get("papers", [])
    if papers:
        story.append(Paragraph("Academic Papers (arXiv)", h2_style))
        for p in papers:
            p_text = f"<b>{p.get('title')}</b><br/>Authors: {p.get('authors')} | Published: {p.get('published')}"
            story.append(Paragraph(p_text, source_title_style))
            story.append(Paragraph(f"URL: {p.get('url')} | Abstract: {p.get('summary')[:180]}...", source_desc_style))
            
    # Web links section
    web_sources = sources_data.get("web_sources", [])
    if web_sources:
        story.append(Spacer(1, 10))
        story.append(Paragraph("Web References (Tavily)", h2_style))
        for w in web_sources:
            w_text = f"<b>{w.get('title')}</b><br/>Source: {w.get('source')} | Credibility: {int(w.get('score', 0.8)*100)}%"
            story.append(Paragraph(w_text, source_title_style))
            story.append(Paragraph(f"URL: {w.get('url')} | Snippet: {w.get('content')[:180]}...", source_desc_style))

    # Build the document
    doc.build(story, canvasmaker=NumberedCanvas)
    print(f"[SUCCESS] PDF report successfully generated at: {file_path}")
    return str(file_path)
